# Log Level
level: info

# Name of this instance for debugging.
node_name: RandomNode

# URL to the web-app
website_url: https://example.com/

# Temporary Folder (for emote uploads)
temp_folder: ""

# Redis Settings
redis:
    uri: redis://username:password@url/db

# MongoDB Settings
mongo:
    uri: mongodb://username:password@url:port/?authSource=db
    db: db

# HTTP Server Settings
http:
    uri: 0.0.0.0:8080
    type: tcp

    # Cookie settings
    cookie_domain: "localhost"
    cookie_secure: false

# RabbitMQ Settings
rmq:
    server_url: ""
    job_queue_name: ""
    result_queue_name: ""
    update_queue_name: ""

aws:
    session_token: ""
    secret_key: ""
    region: ""
    internal_bucket: ""
    public_bucket: ""

# Configure platforms
platforms:
    twitch:
        enabled: true
        client_id: ""
        client_secret: ""
        redirect_uri: ""

# For the JWT signatures.
credentials:
    # A private and public key pair for asymmetrical token generation
    # This is required in order to configure personal emotes
    private_key: pem_encoded_private_key
    public_key: pem_encoded_public_key

    # Standard JWTs
    jwt_secret: ""
