basePath: /v3
definitions:
  model.Emote:
    properties:
      id:
        description: The emote's ID
        type: string
      name:
        description: The emote's name
        type: string
    type: object
host: 7tv.io
info:
  contact:
    email: dev@7tv.io
    name: 7TV Developers
    url: https://discord.gg/7tv
  description: This is the REST API for 7TV
  license:
    name: Apache 2.0 + Commons Clause
    url: https://github.com/SevenTV/REST/blob/dev/LICENSE.md
  termsOfService: TODO
  title: 7TV REST API
  version: "3.0"
paths:
  /emotes:
    get:
      description: Search for emotes
      parameters:
      - description: search by emote name / tags
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Emote'
            type: array
      summary: Search Emotes
      tags:
      - emotes
schemes:
- https
swagger: "2.0"
