name: Build Rest

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  rest:
    name: Build Rest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            "BUILDER=${{ github.actor }}"
            "VERSION=${{ github.sha }}"
          tags: |
            ghcr.io/seventv/rest:${{ github.sha }}
            ghcr.io/seventv/rest:latest
