on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.17]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}

      - name: go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
